export const mockTasks = [
    {
        id: 'task-1',
        title: 'Reunião',
        description: 'Reunião com cliente para apresentação da proposta',
        type: 'Reunião',
        status: 'pending',
        priority: 'high',
        due_date: new Date().toISOString(),
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        assigned_to: 'João Silva',
        opportunity_id: 'deal-1',
        opportunity_name: 'Venda para ACME S.A.',
        created_by: 'Maria Santos',
        responsible: 'João Silva',
        completed: false
    },
    {
        id: 'task-2',
        title: 'Ligação de follow-up',
        description: 'Ligar para cliente após envio da proposta',
        type: 'Ligação',
        status: 'pending',
        priority: 'medium',
        due_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        assigned_to: 'Pedro Costa',
        opportunity_id: 'deal-2',
        opportunity_name: 'Proposta para Beta Ltda.',
        created_by: 'Ana Silva',
        responsible: 'Pedro Costa',
        completed: false
    },
    {
        id: 'task-3',
        title: 'Enviar e-mail de proposta',
        description: 'Enviar proposta comercial por e-mail',
        type: 'E-mail',
        status: 'completed',
        priority: 'high',
        due_date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        assigned_to: 'Carlos Oliveira',
        opportunity_id: 'deal-3',
        opportunity_name: 'Negociação com Gamma Inc.',
        created_by: 'Fernanda Lima',
        responsible: 'Carlos Oliveira',
        completed: true
    },
    {
        id: 'task-4',
        title: 'Follow-up com cliente',
        description: 'Realizar follow-up após reunião',
        type: 'Follow-up',
        status: 'pending',
        priority: 'high',
        due_date: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        assigned_to: 'Ana Silva',
        opportunity_id: 'deal-4',
        opportunity_name: 'Fechamento com Delta S/A',
        created_by: 'Ricardo Mendes',
        responsible: 'Ana Silva',
        completed: false
    },
    {
        id: 'task-5',
        title: 'Demonstração do produto',
        description: 'Apresentar demo ao cliente',
        type: 'Demonstração',
        status: 'pending',
        priority: 'medium',
        due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        assigned_to: 'Juliana Pereira',
        opportunity_id: 'deal-5',
        opportunity_name: 'Apresentação para Epsilon Corp.',
        created_by: 'João Silva',
        responsible: 'Juliana Pereira',
        completed: false
    },
    {
        id: 'task-6',
        title: 'Preparar proposta comercial',
        description: 'Gerar documento de proposta para cliente',
        type: 'Proposta',
        status: 'pending',
        priority: 'low',
        due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        assigned_to: 'Lucas Martins',
        opportunity_id: 'deal-6',
        opportunity_name: 'Proposta para Zeta Ltda.',
        created_by: 'Juliana Pereira',
        responsible: 'Lucas Martins',
        completed: false
    },
    {
        id: 'task-7',
        title: 'Negociação com cliente',
        description: 'Discutir condições comerciais',
        type: 'Negociação',
        status: 'pending',
        priority: 'medium',
        due_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        assigned_to: 'Marina Souza',
        opportunity_id: 'deal-7',
        opportunity_name: 'Negociação com Omega Ltda.',
        created_by: 'Pedro Costa',
        responsible: 'Marina Souza',
        completed: false
    }
];

export const taskTypes = [
    { id: 'Reunião', name: 'Reunião', icon: 'Users' },
    { id: 'E-mail', name: 'E-mail', icon: 'Mail' },
    { id: 'Negociação', name: 'Negociação', icon: 'Handshake' },
    { id: 'Proposta', name: 'Proposta', icon: 'FileText' },
    { id: 'Ligação', name: 'Ligação', icon: 'Phone' },
    { id: 'Follow-up', name: 'Follow-up', icon: 'Clock' },
    { id: 'Demonstração', name: 'Demonstração', icon: 'Monitor' }
]; 