// Flow de exemplo para testes de front

export const mockFlow = {
    id: 'flow-mock-001',
    name: 'Funil de Vendas',
    description: 'Pipeline de vendas padrão para times comerciais.',
    created_by: 'user-mock-001',
    created_at: '2024-04-27T12:00:00Z',
    allowed_entities: ["companies", "people", "partners"],
    stages: [
        {
            id: 'stage-1',
            name: 'Prospecção',
            color: '#2563eb',
            description: 'Primeiro contato com o lead.',
            order_index: 1,
        },
        {
            id: 'stage-2',
            name: 'Apresentação',
            color: '#0ea5e9',
            description: 'Demonstração do produto/serviço.',
            order_index: 2,
        },
        {
            id: 'stage-3',
            name: 'Proposta',
            color: '#f59e42',
            description: 'Envio de proposta comercial.',
            order_index: 3,
        },
        {
            id: 'stage-4',
            name: 'Negociação',
            color: '#fbbf24',
            description: 'Ajustes de valores e condições.',
            order_index: 4,
        },
        {
            id: 'stage-5',
            name: 'Fechamento',
            color: '#22c55e',
            description: 'Contrato fechado e onboarding.',
            order_index: 5,
        },
        {
            id: 'stage-6',
            name: 'Perdido',
            color: '#ef4444',
            description: 'Oportunidade perdida.',
            order_index: 6,
        },
    ],
    deals: [
        {
            id: 'deal-1',
            title: 'Venda para ACME S.A.',
            value: 15000,
            company_id: 'company-1',
            person_id: 'person-1',
            stage_id: 'stage-1',
            position: 1000,
            created_at: '2024-04-27T12:10:00Z',
            tags: ['Importante'],
        },
        {
            id: 'deal-2',
            title: 'Proposta para Beta Ltda.',
            value: 8000,
            company_id: 'company-2',
            person_id: 'person-2',
            stage_id: 'stage-3',
            position: 1000,
            created_at: '2024-04-27T12:20:00Z',
            tags: ['Urgente'],
        },
        {
            id: 'deal-3',
            title: 'Negociação com Gamma Inc.',
            value: 12000,
            company_id: 'company-3',
            person_id: 'person-3',
            stage_id: 'stage-4',
            position: 1000,
            created_at: '2024-04-27T12:30:00Z',
            tags: [],
        },
        {
            id: 'deal-4',
            title: 'Fechamento com Delta S/A',
            value: 20000,
            company_id: 'company-4',
            person_id: 'person-4',
            stage_id: 'stage-5',
            position: 1000,
            created_at: '2024-04-27T12:40:00Z',
            tags: ['VIP'],
        },
    ],
    bases: ['Empresas', 'Contatos'],
};
