// MockUsers.js

export const mockUsers = [
    {
        id: 'user-1',
        first_name: 'João',
        last_name: 'Silva',
        email: 'joao@empresa.com',
        role: 'admin',
        is_active: true,
        client_id: 'client-1',
    },
    {
        id: 'user-2',
        first_name: 'Maria',
        last_name: 'Santos',
        email: 'maria@empresa.com',
        role: 'vendedor',
        is_active: true,
        client_id: 'client-1',
    },
    {
        id: 'user-3',
        first_name: 'Pedro',
        last_name: 'Costa',
        email: 'pedro@empresa.com',
        role: 'vendedor',
        is_active: true,
        client_id: 'client-1',
    },
    {
        id: 'user-4',
        first_name: 'Ana',
        last_name: 'Silva',
        email: 'ana@empresa.com',
        role: 'vendedor',
        is_active: true,
        client_id: 'client-1',
    },
    {
        id: 'user-5',
        first_name: 'Carlos',
        last_name: 'Oliveira',
        email: 'carlos@empresa.com',
        role: 'vendedor',
        is_active: true,
        client_id: 'client-1',
    },
    {
        id: 'user-6',
        first_name: 'Fernanda',
        last_name: 'Lima',
        email: 'fernanda@empresa.com',
        role: 'vendedor',
        is_active: true,
        client_id: 'client-1',
    },
    {
        id: 'user-7',
        first_name: 'Ricardo',
        last_name: 'Mendes',
        email: 'ricardo@empresa.com',
        role: 'vendedor',
        is_active: true,
        client_id: 'client-1',
    },
    {
        id: 'user-8',
        first_name: 'Juliana',
        last_name: 'Pereira',
        email: 'juliana@empresa.com',
        role: 'vendedor',
        is_active: true,
        client_id: 'client-1',
    },
]; 