// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fakjjzrucxpektnhhnjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZha2pqenJ1Y3hwZWt0bmhobmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3ODI3NjEsImV4cCI6MjA1MDM1ODc2MX0.gxITYBXnX-FgrTUQccFsdQaBmUQ6Q_H48GR_QHxMzos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);